spring:

  cache:
    type: simple
  datasource:
    url: jdbc:mysql://67.209.187.223:3306/dbbook?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #格式化输出json
  jackson:
    serialization:
      indent-output: true
server:
  port: 8081
#  servlet:
#          context-path: /rb
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: readingList.domain
logging:
  path: logs/
  file: myLog.log
  level:
    root: info
    readingList: debug
    org.springframework.security: INFO
 
